pipeline {
    agent any
    tools {
        maven "Maven"
        jfrog 'jfrog-cli'
      }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        /*
        stage('Upload to JFrog') {
            steps {
                sh 'jf rt u "target/*.jar" "my-repository/path-in-artifactory/" --build-name=my-build --build-number=${BUILD_NUMBER}'
            }
        }

        stage('Download from JFrog') {
            steps {
                sh 'jf rt dl "my-repository/path-in-artifactory/*.jar" "local-directory/"'
            }
        }*/
        stage('Test') {
            steps {
                echo'Test1'
                sh'mvn test -Dtest="*.java" -Dpublish'
            }
        post{
            success{
                  echo'Test1-success'
                  junit"**/target/surefire-reports/*Devops2.*.xml"
                }
             } 
        }
        stage('Quality Summary') {
            steps {
                withSonarQubeEnv('SonarQubeAkhand') {
                    sh '''
                        mvn sonar:sonar \
                        -Dsonar.projectKey=akhandpratapsingh_ProjectWithTestCases \
                        -Dsonar.host.url=https://sonarcloud.io \
                        -Dsonar.organization=akhandpratapsingh-1 \
                        -Dsonar.login=750ef40825721b9c5fe9d803fd82a0c597cf4de2
                    '''
                }
            }
        }
        stage('Security Summary') {
            steps {
                // sh 'mvn -B package --file pom.xml'
                veracode applicationName: "DevOps Test", criticality: 'VeryHigh', debug: true, timeout: 20, fileNamePattern: '**/**', pHost: '', pPassword: '', pUser: '', replacementPattern: '', sandboxName: '', scanExcludesPattern: '', scanIncludesPattern: '', scanName: "${BUILD_TAG}", uploadExcludesPattern: '', uploadIncludesPattern: '**/**.jar', vid: "5a57339d6779ffb76782e03df3f6e9d1", vkey: "f31d151c427a3286469a6291b14dee15e7f553e066b32c801f09014dc3282de4f51a81cd0bde7c7dd9d95de9a71a32c8a2c582158f278320ae765fe9fd232e0a",waitForScan : true	
            }
        }
        stage('Change') {
            steps {
                echo 'Creating change'
                snDevOpsChange changeRequestDetails: '{ "attributes": { "short_description": "Test description", "priority": "1", "start_date": "2025-03-16 00:00:00", "end_date": "2025-03-16 11:59:00", "justification": "test justification", "description": "test description", "cab_required": true, "comments": "This update for work notes is from jenkins file", "work_notes": "test work notes", "assignment_group": "a715cd759f2002002920bde8132e7018"}, "autoCloseChange": true, "pollingInterval": "10"}'
            }
        }
        stage('Deploy') {
            steps {
                echo "Deploying the application..."
            }
        }
    }
}
