pipeline {
    agent any
    tools {
        maven "Maven"
      }
    stages {
        stage('Build') {
            steps {
                echo "Running tests..."
            }
        }
        stage('Test') {
            steps {
                echo'Test1'
                sh'mvn test -Dtest="*.java" -Dpublish'
            }
        post{
            success{
                  echo'Test1-success'
                  junit"**/target/surefire-reports/*Devops2.*.xml"
                }
             } 
        }
        stage('Upload to JFrog') {
            steps {
                sh 'jf rt u "target/*.jar" "ProjectWithTestCases/path-in-artifactory/" --build-name=my-build --build-number=${BUILD_NUMBER}'
            }
        }

        stage('Download from JFrog') {
            steps {
                sh 'jf rt dl "ProjectWithTestCases/path-in-artifactory/*.jar" "local-directory/"'
            }
        }
        stage('Quality Summary') {
            steps {
                withSonarQubeEnv('SonarQubeAkhand') {
                    sh '''
                        mvn sonar:sonar \
                        -Dsonar.projectKey=akhandpratapsingh_ProjectWithTestCases \
                        -Dsonar.host.url=https://sonarcloud.io \
                        -Dsonar.organization=akhandpratapsingh-1 \
                        -Dsonar.login=750ef40825721b9c5fe9d803fd82a0c597cf4de2
                    '''
                }
            }
        }
        stage('Change') {
            steps {
                echo 'Creating change'
                snDevOpsChange changeRequestDetails: '{ "attributes": { "short_description": "Test description", "priority": "1", "start_date": "2025-03-16 00:00:00", "end_date": "2025-03-16 11:59:00", "justification": "test justification", "description": "test description", "cab_required": true, "comments": "This update for work notes is from jenkins file", "work_notes": "test work notes", "assignment_group": "a715cd759f2002002920bde8132e7018"}, "autoCloseChange": true, "pollingInterval": "10"}'
            }
        }
        stage('Deploy') {
            steps {
                echo "Deploying the application..."
            }
        }
    }
}
