pipeline {
    agent any
    tools {
        maven "Maven"
      }
    stages {
        stage('Build') {
            steps {
                echo "Running tests..."
            }
        }
        stage('Test') {
            steps {
                echo'Test1'
                sh'mvn test -Dtest="Devops2.*" -Dpublish'
            }
        post{
            success{
                  echo'Test1-success'
                  junit"**/target/surefire-reports/*Devops2.*.xml"
                }
             } 
        }
        stage('Deploy') {
            steps {
                echo "Deploying the application..."
            }
        }
    }
}
